$schema: 1.0
name: create-hyper-v-vm
image: microsoftvisualstudio_visualstudioplustools_vs-2022-ent-general-win11-m365-gen2
description: Creates a hyper-V VM
author: Microsoft Corporation
tasks:
  - name: ~/powershell
    parameters:
      command: ".\\create-hyper-v-image.ps1"
documentation:
  notes: This task is used to create a Hyper-V V

